#!/usr/bin/env sh

. "$(dirname "$0")/_/husky.sh"



# Cores
NC='\033[0m' # No Color
# shellcheck disable=SC2034
BBlue='\033[1;34m' # Blue
BRed='\033[1;31m' # Red


REGEX_ISSUE_ID="[a-zA-Z0-9,\.\_\-]+-[0-9]+"
BRANCH_NAME=$(git symbolic-ref --short HEAD)
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")
COMMIT_MESSAGE=$(cat "$1")


if [ -z "$ISSUE_ID" ]; then
    echo "${BRed}Branch não está no padrão que deveria em meu chapa...${NC}"
    exit 1
fi


# shellcheck disable=SC2039
if [[ "$COMMIT_MESSAGE" == "$ISSUE_ID"* ]]; then
    #echo "${BBlue}Tudo certo meu chapa...${NC}"
    exit 0
fi


echo "$ISSUE_ID: $COMMIT_MESSAGE" >$1

