#!/usr/bin/env sh

. "$(dirname "$0")/_/husky.sh"



# run phpstan - larastan
./vendor/bin/phpstan
if [ $? -ne 0 ]; then
    echo "Opa! Parece que temos um problema com o phpstan. Verifique os erros e tente novamente.";

    exit 1;
fi;


# all files modified and formatted using pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep  ".php\{0,1\}$") || true

for FILE in $STAGED_FILES

do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}"

done;

exit 0;
